### PR TITLE
add wasm target

### PR DESCRIPTION
**Pull request by qdsfdhvh**
Closes: #151

### CODE REVIEW

**Comment by sunildhiman90** [comment]
Hi @qdsfdhvh , When will this wasm support be merged?

**Comment by qdsfdhvh** [comment]
> Hi @qdsfdhvh , When will this wasm support be merged?

At the moment I need to wait for `oiko` to provide wasm support before I can possibly publish a preview version, but I still can't merge either, i need to wait until all the wasm for the dependent libraries are released to the official version.

**Comment by qdsfdhvh** [comment]
okio is support wasm, wait for new version. https://github.com/square/okio/pull/1289

**Comment by qdsfdhvh** [comment]
@sunildhiman90 I've just released a version `1.6.4-wasm0`, you can try it out.

**Comment by sunildhiman90** [comment]
Hi thank @qdsfdhvh for notifying me. Actually in current project i delayed the migration of web to wasm becoz i am using some other libraries as well which yet does not support wasm. But I will try it in a separate wasm project very soon. Anyway Thnx for making it compatible with wasm.

**Comment by qdsfdhvh** [comment]
move to https://github.com/qdsfdhvh/compose-imageloader/pull/392

**Pull request closed without merging**
